# Dependencies
markdown:         redcarpet
pygments:         true
#highlighter:      true
# Permalinks
#permalink:        pretty
permalink: /posts/:title
#auto: true
rdiscount:
extensions: [smart]

# Setup
title:            CodePwn
tagline:          'Stuff about Security'
description:      'Stuff about Security'
url:              http://www.codepwn.com
baseurl:          /

author:
  name:           'Pankaj Kohli'
  url:            https://twitter.com/pank4j

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pank4j
